"""Encode the music tracks in assets/music into src/data/music.js as base64 data URIs (looped by the audio engine).
Each track is re-encoded to 44.1 kHz joint-stereo MP3 at 96 kbps to keep the bundle small. Usage: .venv/bin/python tools/music_build.py"""
import base64, json, pathlib, subprocess
ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC, ENC = ROOT / 'assets/music', ROOT / 'assets/music/enc'
# key -> source file in assets/music (owner, 2026-09-26): one track per world to compare, two of them ffmpeg reworks, plus a menu version.
#   w1 first draft as is; w2 ghost lullaby; w3 unwound; w4 unwound-developing-melody pitched down 2 semitones (11% slower), low shelf +3 dB, highs -5 dB;
#   w5 ghost lullaby "underwater": low-pass 1.6 kHz, chorus and a short echo; menu: first draft at 85% tempo, low-passed and 2 dB quieter.
TRACKS = { 'play': 'play_draft1.mp3', 'w1': 'play_draft1.mp3', 'w2': 'ghost_lullaby.mp3', 'w3': 'unwound.mp3', 'w4': 'keep_dark.mp3', 'w5': 'marsh_underwater.mp3', 'menu': 'menu_lobby.mp3' }
def main():
    ENC.mkdir(exist_ok=True); uris, keys = {}, {}
    for key, name in TRACKS.items():
        if name not in uris:   # keys that share a file share one data URI in the bundle
            dst = ENC / (pathlib.Path(name).stem + '.mp3')
            subprocess.run(['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', str(SRC / name), '-ar', '44100', '-ac', '2', '-c:a', 'libmp3lame', '-b:a', '80k', str(dst)], check=True)
            b = dst.read_bytes(); uris[name] = 'data:audio/mpeg;base64,' + base64.b64encode(b).decode()
            print(f'{name} -> {len(b)/1024:.0f} KB')
        keys[key] = name
    names = list(uris)
    js = '// Generated by tools/music_build.py from assets/music. Do not edit by hand.\n'
    js += ''.join(f'const t{i} = {json.dumps(uris[n])};\n' for i, n in enumerate(names))
    js += 'export const MUSIC = { ' + ', '.join(f'{k}: t{names.index(n)}' for k, n in keys.items()) + ' };\n'
    (ROOT / 'src/data/music.js').write_text(js); print('music js', len(js) // 1024, 'KB')
main()
