"""Encode the music tracks in assets/music into src/data/music.js as base64 data URIs (looped by the audio engine).
Each track is re-encoded to 44.1 kHz joint-stereo MP3 at 96 kbps to keep the bundle small. Usage: .venv/bin/python tools/music_build.py"""
import base64, json, pathlib, subprocess
ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC, ENC = ROOT / 'assets/music', ROOT / 'assets/music/enc'
# key -> source file in assets/music (owner, 2026-09-27): a set carved from the owner's "journey 3" drafts (clarinet, bassoon, harp
# orchestrations of one staccato "sneaky" piece) and the "upright bass" drafts. Rendered with ffmpeg from assets/music/drafts:
#   w1 clarinet as is; w2 harp + light echo haze (+6 dB); w3 clarinet and bassoon layered (each ×0.62); w4 bassoon a semitone down,
#   low shelf +2 dB, highs -3 dB; w5 harp underwater: low-pass 1.7 kHz, chorus, short echo (+7 dB);
#   boss: the upright's rising section from 0:36 ("the relay" 0:36-0:56 crossfaded into "theme on upright bass" 0:36-0:56), ~39 s loop;
#   menu: the first draft at 85% tempo, low-passed; play (endless): the clarinet world-1 track.
TRACKS = { 'play': 'w1_patch_clarinet.mp3', 'w1': 'w1_patch_clarinet.mp3', 'w2': 'w2_hollow_harp.mp3', 'w3': 'w3_witchwood_duet.mp3', 'w4': 'w4_keep_bassoon.mp3', 'w5': 'w5_marsh_underwater_harp.mp3', 'boss': 'boss_upright_rising.mp3', 'menu': 'menu_lobby.mp3' }
def main():
    ENC.mkdir(exist_ok=True); uris, keys = {}, {}
    for key, name in TRACKS.items():
        if name not in uris:   # keys that share a file share one data URI in the bundle
            dst = ENC / (pathlib.Path(name).stem + '.mp3')
            subprocess.run(['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', str(SRC / name), '-ar', '44100', '-ac', '2', '-c:a', 'libmp3lame', '-b:a', '80k', str(dst)], check=True)
            b = dst.read_bytes(); uris[name] = 'data:audio/mpeg;base64,' + base64.b64encode(b).decode()
            print(f'{name} -> {len(b)/1024:.0f} KB')
        keys[key] = name
    names = list(uris)
    js = '// Generated by tools/music_build.py from assets/music. Do not edit by hand.\n'
    js += ''.join(f'const t{i} = {json.dumps(uris[n])};\n' for i, n in enumerate(names))
    js += 'export const MUSIC = { ' + ', '.join(f'{k}: t{names.index(n)}' for k, n in keys.items()) + ' };\n'
    (ROOT / 'src/data/music.js').write_text(js); print('music js', len(js) // 1024, 'KB')
main()
