"""Encode the music tracks in assets/music into src/data/music.js as base64 data URIs (looped by the audio engine).
Each track is re-encoded to 44.1 kHz joint-stereo MP3 at 96 kbps to keep the bundle small. Usage: .venv/bin/python tools/music_build.py"""
import base64, json, pathlib, subprocess
ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC, ENC = ROOT / 'assets/music', ROOT / 'assets/music/enc'
TRACKS = { 'play': 'play_draft1.mp3' }   # key -> source file in assets/music
def main():
    ENC.mkdir(exist_ok=True); out = {}
    for key, name in TRACKS.items():
        dst = ENC / f'{key}.mp3'
        subprocess.run(['ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', str(SRC / name), '-ar', '44100', '-ac', '2', '-c:a', 'libmp3lame', '-b:a', '96k', str(dst)], check=True)
        b = dst.read_bytes(); out[key] = 'data:audio/mpeg;base64,' + base64.b64encode(b).decode()
        print(f'{key}: {name} -> {len(b)/1024:.0f} KB')
    js = '// Generated by tools/music_build.py from assets/music. Do not edit by hand.\nexport const MUSIC = ' + json.dumps(out) + ';\n'
    (ROOT / 'src/data/music.js').write_text(js); print('music js', len(js) // 1024, 'KB')
main()
